trigger:
  - release/*
schedules:
- cron: "0 3 * * *"
  displayName: Nigtly build
  branches:
    include:
    - master
  
variables:
  - group: Credentials
  - template: templates/ci/variables.yaml@Scripts

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: Scripts
      type: git
      name: IntDevOpsScripts/ALScripts
    
jobs:
  - job: PrepareEnvironment
    steps:
    - checkout: self
    - checkout: Scripts
    

    - task: PowerShell@2
      name: GetBuildNumber
      displayName: Get Build Number 
      inputs:
        targetType: inline
        script: |
          $manifestContent = Get-Content -Path (Get-Item -path $(Build.SourcesDirectory)\$(Build.Repository.Name)\Apps\**\app.json)[0].FullName | ConvertFrom-Json
          $version = $manifestContent.version
          $appVersion = $version.Substring(0,$version.LastIndexOf('.'))
          Write-Host "##vso[task.setvariable variable=appVersion;isOutput=true]$appVersion"

  - job: Build
    dependsOn: PrepareEnvironment
    variables:
      AppVersion: $[ dependencies.PrepareEnvironment.outputs['GetBuildNumber.AppVersion'] ]
      BuildNo:  $[counter(variables['AppVersion'], 0)]

    strategy:
      matrix:
        NextMinor:
          artifactString: 'bcinsider/sandbox//base/NextMinor'
          InsiderImage: true
          PublishArtifacts: false
          ContainerName: nextminor-$(Build.BuildId)
        NextMajor:
          artifactString: 'bcinsider/sandbox//base/NextMajor'
          InsiderImage: true
          PublishArtifacts: false
          ContainerName: nextmajor-$(Build.BuildId)

    steps:
    - template: templates/ci/preflight.yaml@Scripts
      parameters:
        SkipTargetCheck: true
        SkipTestAppCheck: true
    # - template: templates/ci/install-products.yaml@Scripts
    - template: templates/ci/custom.yaml@Scripts
    - template: templates/ci/postflight.yaml@Scripts